In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [38]:
pdData = pd.read_csv('LogiReg_data.txt',header=None,names=['exam1','exam2','admitted'])
pdData.shape

(100, 3)

In [39]:
pdData.insert(0,'Ones',1)
pdData.head(5)

Ones      exam1      exam2  admitted
0     1  34.623660  78.024693         0
1     1  30.286711  43.894998         0
2     1  35.847409  72.902198         0
3     1  60.182599  86.308552         1
4     1  79.032736  75.344376         1

In [40]:
def sigmod(z):
    return 1/(1+np.exp(-z))

In [53]:
def model(X,theta):
    return sigmod(np.dot(X,theta.T))

In [44]:
orig_data = pdData.as_matrix()

In [45]:
orig_data.shape

(100, 4)

In [46]:
cols_num = orig_data.shape[1]
X=orig_data[:,:cols_num-1]
y=orig_data[:,cols_num-1:cols_num]

In [92]:
X.shape

(100, 3)

In [48]:
y[:3]

array([[0.],
       [0.],
       [0.]])

In [49]:
theta = np.zeros([1,3])

In [50]:
theta

array([[0., 0., 0.]])

In [67]:
def cost(X, y, theta):
    left = np.multiply(-y, np.log(model(X, theta)))
    right = np.multiply(1 - y, np.log(1 - model(X, theta)))
    return np.sum(left - right) / (len(X))

In [68]:
cost(X,y,theta)

0.6931471805599453

In [95]:
def gradient(X, y, theta):
    grad = np.zeros(theta.shape)
    error = (model(X, theta)- y).ravel()
    for j in range(len(theta.ravel())): #for each parmeter
        term = np.multiply(error, X[:,j])
        grad[0, j] = np.sum(term) / len(X)
    
    return grad

In [96]:
gradient(X,y,theta)

array([[ -0.1       , -12.00921659, -11.26284221]])

In [97]:
def descent(data, theta, batchSize, stopType, thresh, alpha):
    # 梯度下降求解

    init_time = time.time()
    i = 0  # 迭代次数
    k = 0  # batch
    X, y = shuffleData(data)
    grad = np.zeros(theta.shape)  # 计算的梯度
    costs = [cost(X, y, theta)]  # 损失值

    while True:
        grad = gradient(X[k:k + batchSize], y[k:k + batchSize], theta)
        k += batchSize  # 取batch数量个数据
        if k >= n:
            k = 0
            X, y = shuffleData(data)  # 重新洗牌
        theta = theta - alpha * grad  # 参数更新
        costs.append(cost(X, y, theta))  # 计算新的损失
        i += 1

        if stopType == STOP_ITER:
            value = i
        elif stopType == STOP_COST:
            value = costs
        elif stopType == STOP_GRAD:
            value = grad
        if stopCriterion(stopType, value, thresh): break

    return theta, i - 1, costs, grad, time.time() - init_time