In [3]:
import numpy as np

In [47]:
A = np.arange(1,5).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [53]:
B = np.arange(0,6).reshape(2,3)
B

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
c = np.dot(A,B)
c

array([[ 6,  9, 12],
       [12, 19, 26]])

In [52]:
c = np.multiply(np.mat(A),np.mat(B))
c

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [20]:
np.sum(c)

20

In [27]:
import pandas as dp

In [44]:
d = dp.DataFrame(A,columns=['aa','bb','cc','dd'])
d

aa  bb  cc  dd
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [46]:
d.iloc[:,0:2]

aa  bb
0   1   2
1   5   6
2   9  10
3  13  14