In [1]:
import numpy as np

In [16]:
a=np.array([1,2,3])
b=np.array([1,2,3])

In [25]:
b=b.reshape(1,3)
b

array([[1, 2, 3]])

In [26]:
a=a.reshape(3,1)
a

array([[1],
       [2],
       [3]])

In [27]:
d=np.dot(a,b)
d

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])